### ISSUE TITLE
tag 是否該翻成 標籤 比較好

### ISSUE THREAD

**Issue by SDLyu** [Csineneo/flarum-ext-traditional-chinese#1]
```
  ref:
    create_tag: 新增節點
    name: 節點名稱
    tags: 節點
```

好奇翻譯成 **節點** 是因為? 😕
